<?php

declare(strict_types=1);

namespace Jengo\Broadcasting\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Jengo\Broadcasting\Broadcast;

class BroadcastTestCommand extends BaseCommand
{
    protected $group       = 'Broadcasting';
    protected $name        = 'broadcast:test';
    protected $description = 'Dispatch a test broadcast event to verify channel connectivity.';
    protected $usage       = 'broadcast:test <channel> <event> [--data=JSON] [--driver=name]';
    protected $arguments   = [
        'channel' => 'The destination channel name (e.g. orders or private-orders.1)',
        'event'   => 'The broadcast event name (e.g. OrderPlaced)',
    ];
    protected $options     = [
        '--data'   => 'Optional JSON payload to broadcast (default: {"test": true, "timestamp": ...})',
        '--driver' => 'Optional specific driver connection to use',
    ];

    public function run(array $params)
    {
        $channel = $params[0] ?? CLI::getOption('channel');
        $event   = $params[1] ?? CLI::getOption('event');

        if (empty($channel) || empty($event)) {
            CLI::error('Both channel and event name are required.');
            CLI::write('Usage: php spark broadcast:test <channel> <event>');
            return;
        }

        $dataRaw = $params['data'] ?? CLI::getOption('data');
        if ($dataRaw === null) {
            foreach ($params as $key => $val) {
                if (is_string($key) && str_starts_with($key, 'data=')) {
                    $dataRaw = substr($key, 5);
                    break;
                }
            }
        }

        $payload = [
            'test'      => true,
            'message'   => 'Test broadcast event generated by Jengo CLI',
            'timestamp' => date('c'),
        ];

        if (is_string($dataRaw) && $dataRaw !== '') {
            $parsed = json_decode($dataRaw, true);
            if (is_array($parsed)) {
                $payload = array_merge($payload, $parsed);
            }
        }

        $driver = $params['driver'] ?? CLI::getOption('driver');
        if ($driver === null) {
            foreach ($params as $key => $val) {
                if (is_string($key) && str_starts_with($key, 'driver=')) {
                    $driver = substr($key, 7);
                    break;
                }
            }
        }
        $manager = Broadcast::getFacadeRoot();

        if (is_string($driver) && $driver !== '') {
            $broadcaster = $manager->driver($driver);
        } else {
            $broadcaster = $manager->connection();
        }

        CLI::write("Broadcasting [{$event}] to [{$channel}] using [" . get_class($broadcaster) . "]...", 'cyan');

        try {
            $broadcaster->broadcast([$channel], $event, $payload);
            CLI::write('Broadcast dispatched successfully.', 'green');
            CLI::write('Payload: ' . json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        } catch (\Throwable $e) {
            CLI::error('Broadcast dispatch failed: ' . $e->getMessage());
        }
    }
}
